/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bubble_only.glb -o src/models/Bubbleonly.jsx 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export const BubbleOnly = (props) => {
  const { nodes, materials } = useGLTF("/Bubble_only.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials["Material.005"]}
        position={[-19.508, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload("/Bubble_only.glb");

export default BubbleOnly;
