/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bubble_feather.glb -o src/models/Bubblefeather.jsx 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Group } from "three";

interface BubbleFeatherProps {}

const BubbleFeather = (props: BubbleFeatherProps) => {
  const group = React.useRef<Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "./models/Bubble_feather.glb",
  );
  useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cylinder021"
          geometry={(nodes.Cylinder021 as any).geometry}
          material={materials["Material.006"]}
          position={[-26.751, -0.706, 0.304]}
          rotation={[-0.566, 0.458, 0.274]}
        />
        <mesh
          name="Mesh002"
          geometry={(nodes.Mesh002 as any).geometry}
          material={(nodes.Mesh002 as any).material}
          position={[-26.751, -0.706, 0.304]}
          rotation={[0, 0.529, 0]}
        />
        <mesh
          name="Mesh003"
          geometry={(nodes.Mesh003 as any).geometry}
          material={(nodes.Mesh003 as any).material}
          position={[-26.751, -0.706, 0.304]}
          rotation={[0, 0.529, 0]}
        />
        <mesh
          name="Sphere"
          geometry={(nodes.Sphere as any).geometry}
          material={materials["Material bubble glass"]}
          position={[-26.518, 0.565, -0.069]}
          scale={4.469}
        />
      </group>
    </group>
  );
};

useGLTF.preload("./models/Bubble_feather.glb");

export default BubbleFeather;
