/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/feather.glb -o src/models/Feather.jsx 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Group, Mesh } from "three";

interface FeatherGLBProps {
  [key: string]: any;
}

const FeatherGLB = (props: FeatherGLBProps) => {
  const group = React.useRef<Group>(null);
  const { nodes, materials, animations } = useGLTF("./models/feather.glb");
  useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cylinder021"
          geometry={(nodes.Cylinder021 as Mesh).geometry}
          material={materials["Material.006"]}
          position={[-26.751, -0.706, 0.304]}
          rotation={[-0.566, 0.458, 0.274]}
        />
        <mesh
          name="Mesh002"
          geometry={(nodes.Mesh002 as Mesh).geometry}
          material={(nodes.Mesh002 as Mesh).material}
          position={[-26.751, -0.706, 0.304]}
          rotation={[0, 0.529, 0]}
        />
        <mesh
          name="Mesh003"
          geometry={(nodes.Mesh003 as Mesh).geometry}
          material={(nodes.Mesh003 as Mesh).material}
          position={[-26.751, -0.706, 0.304]}
          rotation={[0, 0.529, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("./models/feather.glb");
export default FeatherGLB;
