/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/featherkb.glb -o src/models/featherkb.jsx 
*/


import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";


const FeatherKB = (props: any) => {
  const { nodes, materials } = useGLTF("/assets/models/featherkb.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Mesh0 as Mesh).geometry}
        material={materials.BakedMaterial}
        position={[0.002, -0.002, 0]}
      />
    </group>
  );
};

useGLTF.preload("/assets/models/featherkb.glb");

export default FeatherKB;
